version: 2
jobs:
  BAT:
    docker:
      - image: dockcross/windows-x64
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            call project/coreTest.bat


workflows:
    version: 2
    run_ci:
        jobs:
            - BAT
