name: windows

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions


jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        examples:
          - "project/coreTest.bat"
          - "project/demo_at_engine.bat"
          - "project/demo_bluetooth.bat"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build
        run: |
          call ${{ matrix.examples }}
